/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarComponent: typeof import('./src/components/AvatarComponent.vue')['default']
    ChatComponent: typeof import('./src/components/Layout/ChatComponent.vue')['default']
    IncrementorComponent: typeof import('./src/components/IncrementorComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
